apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: call-center
  labels:
    app.kubernetes.io/name: celery-beat
    app.kubernetes.io/part-of: call-center
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celery-beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: celery-beat
        app.kubernetes.io/part-of: call-center
        app.kubernetes.io/component: scheduler
    spec:
      containers:
        - name: celery-beat
          image: call-center/call-processor:latest
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - "-A"
            - src.tasks.celery_app
            - beat
            - "-l"
            - info
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: call-center-config
            - secretRef:
                name: call-center-secrets
